### ISSUE TITLE
[BUG] HTML minify not working anymore due to update of html-minifier-terser

### ISSUE THREAD

**Issue by Chris2011** [Chris2011/minifierbeans#88]
**Describe the bug**
When I minfy an HTML file with latest Minifierbeans 3.4.0 plugin I got this error on the command line and the minified html file is empty:

```
C:\Users\Chris\Downloads>html-minifier-terser index.html --output index.min.html
internal/streams/writable.js:285
      throw new ERR_INVALID_ARG_TYPE(
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Promise
←[90m    at WriteStream.Writable.write (internal/streams/writable.js:285:13)←[39m
    at writeMinify (C:\Users\Chris\AppData\Roaming\npm\node_modules\←[4mhtml-minifier-terser←[24m\cli.js:288:24)
    at Object.<anonymous> (C:\Users\Chris\AppData\Roaming\npm\node_modules\←[4mhtml-minifier-terser←[24m\cli.js:305:3)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'ERR_INVALID_ARG_TYPE'←[39m
}
```

**To Reproduce**
1. Install Minifierbeans 3.4.0
2. Choose an HTML file
3. Right click on this file and choose 'Minify HTML'

**Expected behavior**
Everything should be fine.

This is happening of html-minifier-terser version 6.0.0. See: https://github.com/terser/html-minifier-terser/issues/71

**Comment by Chris2011** [comment]
Bug in html-minifier-terser was fixed, updated dependencies. So it is working again in latest release 3.4.0 which is the same.
